### ISSUE TITLE
Build error after recent changes

### ISSUE THREAD

**Issue by meriadec** [LedgerHQ/lib-ledger-core-node-bindings#19]
On branch develop, here is what I get when `yarn`:

```
[...]
../node_modules/nan/nan_object_wrap.h:38:12: error: ‘Nan::ObjectWrap’ is an inaccessible base of ‘djinni::js::ObjectWrapper<ledger::core::api::BitcoinLikeTransactionBuilder>’
     return static_cast<T*>(wrap);
[...]
```

I guess it's related to [recent changes](https://github.com/LedgerHQ/lib-ledger-core-node-bindings/pull/18). I don't understand why I didn't reproduced yesterday.

@teams2ua does it ring a bell?

**Comment by teams2ua** [comment]
This is bug in MSVC compiler that can't catch the error for me
https://godbolt.org/z/A09pR6
try to switch to gcc to see the error.
Fix is here
https://github.com/LedgerHQ/lib-ledger-core-node-bindings/pull/20
